# Generated by Django 3.0.7 on 2020-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='givenName',
            field=models.CharField(default='testgivenname', max_length=180),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='testname', max_length=180),
        ),
    ]
