# Generated by Django 3.0.7 on 2020-06-23 20:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sim.modelFields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateupdated', models.DateTimeField(auto_now=True)),
                ('simtime', models.PositiveSmallIntegerField(default=0)),
                ('patients', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), size=5), size=None)),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=4), size=None)),
                ('totalmean', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), size=3)),
                ('ventmean', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(default=0), size=3)),
                ('narrivals', models.PositiveSmallIntegerField(default=0)),
                ('mortrate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), size=3)),
                ('output', sim.modelFields.JSONSchemaField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
