# Generated by Django 3.0.7 on 2020-06-23 21:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_auto_20200623_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='datecreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sim',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='name',
            field=models.CharField(default='test name', max_length=200),
        ),
        migrations.AlterField(
            model_name='sim',
            name='input',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
