# Generated by Django 3.0.7 on 2020-06-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20200623_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='dateupdated',
        ),
        migrations.AddField(
            model_name='sim',
            name='description',
            field=models.CharField(default='test description', max_length=200),
        ),
    ]
