# Generated by Django 3.0.7 on 2020-06-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_auto_20200625_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim',
            old_name='datecreated',
            new_name='date_created',
        ),
    ]
