# Generated by Django 3.0.7 on 2020-06-26 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_auto_20200625_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sim',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sim',
            name='tend',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
