# Generated by Django 3.0.7 on 2020-07-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0008_auto_20200715_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim',
            old_name='simTime',
            new_name='simDays',
        ),
    ]
