# Generated by Django 3.1.2 on 2020-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0009_auto_20200717_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='daysEcmo_cat2',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='daysEcmo_cat3',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='daysVent_cat1',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='daysVent_cat3',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
